import { useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { Banknote, CalendarRange, Check, Clock3, CopyPlus, LockKeyhole, Percent, Settings2 } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { isDemoMode, supabase } from '../../lib/supabase';
import { formatNaira, planTotalKobo } from '../../lib/money';
import { Button, PageHeader, StatusBadge } from '../../components/ui';
import { surchargeRates } from '../../lib/surchargeRates';
import { zonedInputToIso, zonedInputValue } from '../../lib/format';

export function AdminSettingsPage() {
  const { snapshot, updatePeriod, updatePaymentAccount, updateProgramTimezone, updateSurchargeRates } = useApp();
  const [period, setPeriod] = useState(snapshot!.period);
  const [account, setAccount] = useState(snapshot!.paymentAccount);
  const [saving, setSaving] = useState('');
  const [timezone, setTimezone] = useState(snapshot!.program.timezone);
  const [rates, setRates] = useState(() => surchargeRates(snapshot!.period));
  const savePeriod = async (event: FormEvent) => { event.preventDefault(); if (snapshot!.period.status !== 'closed' && period.status === 'closed' && !window.confirm('Close this enrollment period? Subscribers will no longer be able to change or submit details.')) return; setSaving('period'); try { await updatePeriod(period); } finally { setSaving(''); } };
  const saveRates = async (event: FormEvent) => { event.preventDefault(); if (!window.confirm('Apply these surcharge rates and recalculate every enrollment total for this year? Existing payment records will be preserved.')) return; setSaving('rates'); try { await updateSurchargeRates(rates); } finally { setSaving(''); } };
  const saveTimezone = async (event: FormEvent) => { event.preventDefault(); setSaving('timezone'); try { await updateProgramTimezone(timezone); } finally { setSaving(''); } };
  const saveAccount = async (event: FormEvent) => { event.preventDefault(); setSaving('account'); try { await updatePaymentAccount(account); } finally { setSaving(''); } };
  const createNextYear = async () => { if (!supabase || isDemoMode) return; setSaving('next'); const nextYear = period.year + 1; const { error } = await supabase.rpc('create_next_enrollment_year', { p_source_period_id: period.id, p_year: nextYear, p_starts_at: `${nextYear}-06-01T00:00:00+01:00`, p_ends_at: `${nextYear}-08-31T23:59:59+01:00` }); setSaving(''); if (error) window.alert(error.message); else window.location.reload(); };

  return <>
    <PageHeader eyebrow="Owner settings" title="Program settings" description="Configuration changes are versioned and recorded in the audit history." actions={<StatusBadge status={snapshot!.period.status} />} />
    <div className="settings-layout">
      <section className="settings-nav panel"><a href="#timezone"><Clock3 size={18} />Time zone</a><a href="#surcharges"><Percent size={18} />Surcharges</a><a href="#period"><CalendarRange size={18} />Enrollment period</a><a href="#offerings"><Settings2 size={18} />Plan offerings</a><a href="#payment-account"><Banknote size={18} />Payment account</a><a href="#access"><LockKeyhole size={18} />Access control</a></section>
      <div className="settings-content">
        <form id="timezone" className="form-section" onSubmit={saveTimezone}><div className="section-heading"><span><Clock3 size={20} /></span><div><h2>Program time zone</h2><p>All deadlines, activity, and reports use this time zone.</p></div></div><label>Time zone<select value={timezone} onChange={(event) => setTimezone(event.target.value)}><option value="Africa/Lagos">Africa/Lagos (WAT)</option><option value="Europe/London">Europe/London</option><option value="America/New_York">America/New_York</option><option value="America/Chicago">America/Chicago</option><option value="America/Los_Angeles">America/Los_Angeles</option><option value="Asia/Dubai">Asia/Dubai</option></select></label><div className="form-actions"><Button disabled={saving === 'timezone'} icon={<Check size={17} />}>{saving === 'timezone' ? 'Saving…' : 'Save time zone'}</Button></div></form>
        <form id="surcharges" className="form-section" onSubmit={saveRates}><div className="section-heading"><span><Percent size={20} /></span><div><h2>{period.year} surcharge rates</h2><p>Rates apply to this enrollment year. Saving recalculates totals and outstanding balances without changing payment records.</p></div></div><div className="form-grid surcharge-rate-grid"><label>AVON NHIS fee (%)<input required type="number" min="0" max="100" step="0.01" value={rates.nhisFeeBasisPoints / 100} onChange={(event) => setRates({ ...rates, nhisFeeBasisPoints: Math.round(Number(event.target.value) * 100) })} /></label><label>Program administrative fee (%)<input required type="number" min="0" max="100" step="0.01" value={rates.programFeeBasisPoints / 100} onChange={(event) => setRates({ ...rates, programFeeBasisPoints: Math.round(Number(event.target.value) * 100) })} /></label></div><div className="form-actions"><Button disabled={saving === 'rates'} icon={<Check size={17} />}>{saving === 'rates' ? 'Saving…' : 'Save surcharge rates'}</Button></div></form>
        <form id="period" className="form-section" onSubmit={savePeriod}><div className="section-heading"><span><CalendarRange size={20} /></span><div><h2>Enrollment period</h2><p>Dates use {snapshot!.program.timezone} time.</p></div></div><div className="form-grid"><label>Coverage year<input type="number" readOnly value={period.year} /></label><label>Status<select value={period.status} onChange={(e) => setPeriod({ ...period, status: e.target.value as typeof period.status })}><option value="scheduled">Scheduled</option><option value="open">Open</option><option value="closed">Closed</option></select></label><label>Opens<input type="datetime-local" value={zonedInputValue(period.startsAt, snapshot!.program.timezone)} onChange={(e) => setPeriod({ ...period, startsAt: zonedInputToIso(e.target.value, snapshot!.program.timezone) })} /></label><label>Closes<input type="datetime-local" value={zonedInputValue(period.endsAt, snapshot!.program.timezone)} onChange={(e) => setPeriod({ ...period, endsAt: zonedInputToIso(e.target.value, snapshot!.program.timezone) })} /></label><label className="span-2">Extension or closure note<textarea rows={2} value={period.extensionNote ?? ''} onChange={(e) => setPeriod({ ...period, extensionNote: e.target.value })} /></label></div><div className="form-actions"><Button disabled={saving === 'period'} icon={<Check size={17} />}>{saving === 'period' ? 'Saving…' : 'Save period'}</Button></div></form>
        <section id="offerings" className="form-section"><div className="section-heading"><span><Settings2 size={20} /></span><div><h2>{period.year} plan offerings</h2><p>Totals use the surcharge rates configured above. Current-year prices are preserved when a new period is created.</p></div></div><div className="settings-plan-list">{snapshot!.plans.map((plan) => <div key={plan.id}><span><strong>{plan.name}</strong><small>{plan.region}</small></span><span><small>Individual total</small><strong>{formatNaira(planTotalKobo(plan.individualPremiumKobo, rates))}</strong></span><span><small>Family total</small><strong>{formatNaira(planTotalKobo(plan.familyPremiumKobo, rates))}</strong></span><StatusBadge status={plan.active ? 'Active' : 'Inactive'} /></div>)}</div><div className="form-actions"><Button variant="secondary" icon={<CopyPlus size={17} />} disabled={isDemoMode || saving === 'next'} onClick={() => void createNextYear()}>{saving === 'next' ? 'Creating…' : 'Create next enrollment year'}</Button></div></section>
        <form id="payment-account" className="form-section" onSubmit={saveAccount}><div className="section-heading"><span><Banknote size={20} /></span><div><h2>Payment account</h2><p>Subscribers see the active account during payment.</p></div></div><div className="form-grid"><label>Account name<input required value={account.beneficiary} onChange={(e) => setAccount({ ...account, beneficiary: e.target.value })} /></label><label>Bank<input required value={account.bank} onChange={(e) => setAccount({ ...account, bank: e.target.value })} /></label><label>Account number<input required inputMode="numeric" pattern="[0-9]{10}" value={account.accountNumber} onChange={(e) => setAccount({ ...account, accountNumber: e.target.value.replace(/\D/g, '').slice(0, 10) })} /></label><label>Reference prefix<input required value={account.referencePrefix} onChange={(e) => setAccount({ ...account, referencePrefix: e.target.value })} /></label></div><div className="form-actions"><Button disabled={saving === 'account'} icon={<Check size={17} />}>{saving === 'account' ? 'Saving…' : 'Save payment account'}</Button></div></form>
        <section id="access" className="form-section"><div className="section-heading"><span><LockKeyhole size={20} /></span><div><h2>Access control</h2><p>Only the owner can change administrator access.</p></div></div><div className="access-list"><div><span className="person-dot">U</span><span><strong>Program owner</strong><small>Owner account</small></span><StatusBadge status="Active" /></div><div><span className="person-dot">A</span><span><strong>Administrator</strong><small>Payment and enrollment administration</small></span><StatusBadge status="Active" /></div><div><span className="person-dot">A</span><span><strong>Administrator</strong><small>Payment and enrollment administration</small></span><StatusBadge status="Active" /></div></div><div className="form-actions"><Link className="button button--secondary" to="/admin/access">Manage administrators</Link></div></section>
      </div>
    </div>
  </>;
}
