import { useState, type FormEvent } from 'react';
import { Banknote, CalendarRange, Check, CopyPlus, LockKeyhole, Settings2 } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { formatNaira, planTotalKobo } from '../../lib/money';
import { Button, PageHeader, StatusBadge } from '../../components/ui';

export function AdminSettingsPage() {
  const { snapshot, updatePeriod, updatePaymentAccount } = useApp();
  const [period, setPeriod] = useState(snapshot!.period);
  const [account, setAccount] = useState(snapshot!.paymentAccount);
  const [saving, setSaving] = useState('');
  const savePeriod = async (event: FormEvent) => { event.preventDefault(); setSaving('period'); try { await updatePeriod(period); } finally { setSaving(''); } };
  const saveAccount = async (event: FormEvent) => { event.preventDefault(); setSaving('account'); try { await updatePaymentAccount(account); } finally { setSaving(''); } };

  return <>
    <PageHeader eyebrow="Owner settings" title="Program settings" description="Configuration changes are versioned and recorded in the audit history." actions={<StatusBadge status={snapshot!.period.status} />} />
    <div className="settings-layout">
      <section className="settings-nav panel"><a href="#period"><CalendarRange size={18} />Enrollment period</a><a href="#offerings"><Settings2 size={18} />Plan offerings</a><a href="#payment-account"><Banknote size={18} />Payment account</a><a href="#access"><LockKeyhole size={18} />Access control</a></section>
      <div className="settings-content">
        <form id="period" className="form-section" onSubmit={savePeriod}><div className="section-heading"><span><CalendarRange size={20} /></span><div><h2>Enrollment period</h2><p>Dates use Africa/Lagos time.</p></div></div><div className="form-grid"><label>Coverage year<input type="number" value={period.year} onChange={(e) => setPeriod({ ...period, year: Number(e.target.value) })} /></label><label>Status<select value={period.status} onChange={(e) => setPeriod({ ...period, status: e.target.value as typeof period.status })}><option value="scheduled">Scheduled</option><option value="open">Open</option><option value="closed">Closed</option></select></label><label>Opens<input type="datetime-local" value={period.startsAt.slice(0, 16)} onChange={(e) => setPeriod({ ...period, startsAt: e.target.value })} /></label><label>Closes<input type="datetime-local" value={period.endsAt.slice(0, 16)} onChange={(e) => setPeriod({ ...period, endsAt: e.target.value })} /></label><label className="span-2">Extension or closure note<textarea rows={2} value={period.extensionNote ?? ''} onChange={(e) => setPeriod({ ...period, extensionNote: e.target.value })} /></label></div><div className="form-actions"><Button disabled={saving === 'period'} icon={<Check size={17} />}>{saving === 'period' ? 'Saving…' : 'Save period'}</Button></div></form>
        <section id="offerings" className="form-section"><div className="section-heading"><span><Settings2 size={20} /></span><div><h2>{period.year} plan offerings</h2><p>Current-year prices are preserved when a new period is created.</p></div></div><div className="settings-plan-list">{snapshot!.plans.map((plan) => <div key={plan.id}><span><strong>{plan.name}</strong><small>{plan.region}</small></span><span><small>Individual total</small><strong>{formatNaira(planTotalKobo(plan.individualPremiumKobo))}</strong></span><span><small>Family total</small><strong>{formatNaira(planTotalKobo(plan.familyPremiumKobo))}</strong></span><StatusBadge status={plan.active ? 'Active' : 'Inactive'} /></div>)}</div><div className="form-actions"><Button variant="secondary" icon={<CopyPlus size={17} />}>Create next enrollment year</Button></div></section>
        <form id="payment-account" className="form-section" onSubmit={saveAccount}><div className="section-heading"><span><Banknote size={20} /></span><div><h2>Payment account</h2><p>Subscribers see the active account during payment.</p></div></div><div className="form-grid"><label>Account name<input required value={account.beneficiary} onChange={(e) => setAccount({ ...account, beneficiary: e.target.value })} /></label><label>Bank<input required value={account.bank} onChange={(e) => setAccount({ ...account, bank: e.target.value })} /></label><label>Account number<input required inputMode="numeric" pattern="[0-9]{10}" value={account.accountNumber} onChange={(e) => setAccount({ ...account, accountNumber: e.target.value.replace(/\D/g, '').slice(0, 10) })} /></label><label>Reference prefix<input required value={account.referencePrefix} onChange={(e) => setAccount({ ...account, referencePrefix: e.target.value })} /></label></div><div className="form-actions"><Button disabled={saving === 'account'} icon={<Check size={17} />}>{saving === 'account' ? 'Saving…' : 'Save payment account'}</Button></div></form>
        <section id="access" className="form-section"><div className="section-heading"><span><LockKeyhole size={20} /></span><div><h2>Access control</h2><p>Only the owner can change administrator access.</p></div></div><div className="access-list"><div><span className="person-dot">U</span><span><strong>Program owner</strong><small>Owner account</small></span><StatusBadge status="Active" /></div><div><span className="person-dot">A</span><span><strong>Administrator</strong><small>Payment and enrollment administration</small></span><StatusBadge status="Active" /></div><div><span className="person-dot">A</span><span><strong>Administrator</strong><small>Payment and enrollment administration</small></span><StatusBadge status="Active" /></div></div><div className="form-actions"><Button variant="secondary">Manage administrators</Button></div></section>
      </div>
    </div>
  </>;
}
